# Generated by Django 5.2 on 2025-05-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_productreview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('cart', 'Shopping Cart'), ('payment', 'Awaiting Payment'), ('shipping', 'Awaiting Shipment'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='cart', help_text='Status'),
        ),
    ]
