# Generated by Django 5.2 on 2025-05-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_order_product_remove_order_quantity_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_product',
            new_name='OrderProduct',
        ),
    ]
